### ISSUE TITLE
CP ignores the search path specified

### ISSUE THREAD

**Issue by Mahmoud87** [linuxserver/docker-couchpotato#12]
Hello, I just noticed that CP does't really look in the directory you specify however only search in /downloads and anything after that. In my case I have /(shared directory)/Movies/ and under this directory there is 2 folders [Arabic and English Movies] I specified the path for the English movies
/download/Movies/English Movies, CP just looks under the /downloads and bring up everything rather than the specified path. I am not sure if this is a bug or am I doing something wrong?

> ![cp](https://cloud.githubusercontent.com/assets/20716439/17618649/12edc1bc-60c0-11e6-84f6-5dde63961d13.jpg).

The other thing When I try thing to browse to the directory the browse menu doesn't fully appear pretty much unusable I have to type the full directory myself as it shows in the picture below.

> ![cp2](https://cloud.githubusercontent.com/assets/20716439/17623100/93a7bfca-60dd-11e6-97d7-78fb7c189c9f.jpg)

Thanks :)

**Comment by j0nnymoe** [comment]
With the downloads folder search, I would probably suggest to move your media out from under the /downloads/ folder and mount it to the /movies/ volume. The /downloads folder is only ever intended for temp files. (See our docker readme for the -v mounts again)

On the second screenshot, from what I recall, the menu can be flaky, typing it in is probably best.

**Comment by Mahmoud87** [comment]
Thanks for you reply, do you mean to create a new share and just name it to /movies? cause the other docker images I use they use the mapped directories fine however I did that and had the path to be /movies then the rest of the directory for my movies, so I have used "/movies/media/movies/english movies" and still doing the same thing and it grabs everything under the /movies ignoring the specified path.

> On the second screenshot, from what I recall, the menu can be flaky, typing it in is probably best.
Is there any plans to get it fixed soon? Thanks again for replying so quick.

**Comment by j0nnymoe** [comment]
I would just keep any of your download folders separate to any media folders, if anything just to keep it clean. 

if its a bug with couchpotato, it's out of our hands though if it can be proven its an issue with our container, we will look into it :)

**Comment by Mahmoud87** [comment]
Fair enough mate, I guess its more likely a bug in CP itself not the container, I wasn't sure if you guys deal with the devs of CP directly or not this is why I posted this issue here :),  and hopefully CP release a new ver and get this fixed. I think I will start creating new shares and split media from download instead of having everything under one share.
