### ISSUE TITLE
Web UI can't load

### ISSUE THREAD

**Issue by Mahmoud87** [linuxserver/docker-couchpotato#18]
Hi guys, I have been using CP for a while now and all of a sudden it stopped loading the webui. I have tried reinstalling it multiple times no luck I get "This site can’t be reached" message on chrome also tried on a different browser same thing.

I am using couchpotato rockon on Rockstor.

This is the most logs I can get.

> Traceback (most recent call last):
>   File "/app/couchpotato/CouchPotato.py", line 133, in <module>
>     l = Loader()
>   File "/app/couchpotato/CouchPotato.py", line 64, in __init__
>     hdlr = handlers.RotatingFileHandler(os.path.join(self.log_dir, 'error.log'), 'a', 500000, 10)
>   File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
>     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
>   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
>     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
>   File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
>     StreamHandler.__init__(self, self._open())
>   File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
>     stream = open(self.baseFilename, self.mode)
> IOError: [Errno 13] Permission denied: '/config/data/logs/error.log'

Thanks

**Comment by Mahmoud87** [comment]
[Solved] installed in a different share on Rockstor and worked fine. I had to delete the data folder that have CP settings and reinstalled CP rockon again in the original share and worked perfectly fine.

**Comment by sparklyballs** [comment]
thanks for the update, i'll close this one out.
