### ISSUE TITLE
Unable to remove or change quality of movie

### ISSUE THREAD

**Issue by jsorondo** [linuxserver/docker-couchpotato#22]
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(CouchPotato:CouchPotatoServer master) 0a97ed5a (2017-06-26 06:29:35)
Running on: ...

### Logs:
```
06-28 00:25:38 ERROR [   couchpotato.core.event] Error in event "release.for_media", that wasn't caught: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/app/couchpotato/couchpotato/core/plugins/release/main.py", line 554, in forMedia
    doc = db.get('id', r.get('_id'))
  File "/app/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/app/couchpotato/libs/CodernityDB/database.py", line 942, in get
    raise RecordNotFound(ex)
RecordNotFound: Location 'dce7112d5b2c41f19eb6aab03679235e' not found
encoding=UTF-8 debug=False args=['--config_file=/config/config.ini', '--data_dir=/config/data'] app_dir=/app/couchpotato data_dir=/config/data desktop=None options=Namespace(config_file='/config/config.ini', console_log=False, daemon=False, data_dir='/config/data', debug=False, pid_file='/config/data/couchpotato.pid', quiet=False)  
```

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by j0nnymoe** [comment]
We also need any information that for the questions that were in the issue template:

Host OS
Command line users, your run/create command, GUI/Unraid users, a screenshot of your template settings.
Docker log output, docker log <container-name>
Mention if you're using symlinks on any of the volume mounts.

**Comment by j0nnymoe** [comment]
No response. Closing issue.
