### ISSUE TITLE
Couldn’t connect to download station

### ISSUE THREAD

**Issue by nicduch** [linuxserver/docker-couchpotato#29]
impossible to use download station as downloader. Error at connection test.

Log:

[core.downloaders.synology] Couldn't log into Synology, {u'success': False, u'error': "{u'code': 402}"}

Any idea?

**Comment by sparklyballs** [comment]
more information would be a good idea to start with, lol

for instance which ip you're using to try and connect to the downloader with, whether you're using the container in host or bridge mode etc (paste a screenie of your settings in the synology webui)

**Comment by nicduch** [comment]
192.168.1.249:5000 the same that i access to DSM desktop.

login et password same as login and password admin that i use to login to DSM Desktop session...

all my container are in bridge mode

**Comment by j0nnymoe** [comment]
Assuming this is no longer an issue. If this is still an issue, please re-open the ticket and we'll try and look into this further.

**Comment by michaeltieso** [comment]
Hey. I'm having the same issue. What info do you need to help troubleshoot?

**Comment by j0nnymoe** [comment]
Hi, docker run info + connection info that you are putting in for download station.
(warning - no one in the team has a synology device so support is limited.)

**Comment by aphentik** [comment]
Hello, I confirm that I've got the same issue due two 2 step auth. I guess that best practice is to create a dedicated account with low access right to data to be used as "service account"

**Comment by decharon** [comment]
I also have the some problem:

[core.downloaders.synology] Couldn't log into Synology, {u'success': False, u'error': "{u'code': 103}"}

I have no problems connecting to SickChill on the docker.

**Comment by j0nnymoe** [comment]
@decharon I would ask upstream at the couchpotato repo instead of here. It's not going to be related to the container but rather couchpotato instead.

**Comment by decharon** [comment]
Thanks i will give that a try
