### ISSUE TITLE
Changing PUID to 65534 prevents the container to start

### ISSUE THREAD

**Issue by ybizeul** [linuxserver/docker-couchpotato#3]
When setting the PUID to 65535 the container crashes when tryint to run the update at startup because it can't fetch the git repository

**Comment by sparklyballs** [comment]
what host ?
just running 
docker run -d --name=test -e PUID=65534 -e PGID=100 --net=host linuxserver/couchpotato
and the container starts up fine and pulls the git repository.
running on ubuntu 14.04 VM

**Comment by sparklyballs** [comment]
and 
docker run -d --name=test -e PUID=65535 -e PGID=100 --net=host linuxserver/couchpotato

even works too, lol.
just saw i had the wrong port the first time.

**Comment by JTarasovic** [comment]
I use nogroup for my service users and don't have any problems with these images.

**Comment by ybizeul** [comment]
Sorry for the lag. The host was Synology, I'm not sure it still current. I'll report if I have this problem again
