### ISSUE TITLE
No permissions to /movies on Synology DS 718+

### ISSUE THREAD

**Issue by theilgaard** [linuxserver/docker-couchpotato#34]
### Steps to reproduce:
1. Run couchpotato in docker on synology
2. Mount a shared dir as /movies in container with +RW
3. Try to select /movies destination dir for renamer.

Version of CouchPotato: git:(CouchPotato:CouchPotatoServer master) 12ca4c22 (2018-03-31 21:29:42)
Running on: Docker container (linuxserver/couchpotato) on Synology Disk Station DS 718+ 

### Logs:
```
04-09 15:26:13 ERROR [tato.core.plugins.browser] Failed getting directory "/movies/" : Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 96, in view
    dirs = self.getDirectories(path = path, show_hidden = show_hidden)
  File "/app/couchpotato/couchpotato/core/plugins/browser.py", line 60, in getDirectories
    for f in os.listdir(path):
OSError: [Errno 13] Permission denied: '/movies'
 
```

I am able to create and remove dirs on the mounted volume. 

```
root@couchpotato1:/movies$ mkdir test                                                                                
root@couchpotato1:/movies$ rmdir test                                                                                
```

**Comment by sparklyballs** [comment]
logged in as root well of course you can make folders 

the folders concerned need to be owned by the user you're running the docker as

**Comment by theilgaard** [comment]
Thanks. I changed the PGID environment variable, as specified on https://hub.docker.com/r/linuxserver/couchpotato/ to a group with access to the volume and it worked.
