### ISSUE TITLE
I can't seem to get jackett to work with CP

### ISSUE THREAD

**Issue by jang430** [linuxserver/docker-couchpotato#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 Unraid 6.5.3 running docker 17.09.1-ce

no

I keep on getting something like this-

08-06 22:37:07 ERROR [hpotato.core.plugins.base] Failed opening url in TorrentPotato: magnetdl?imdbid=tt8497714&search=Hailey+Dean+Mystery%3A+A+Marriage+Made+for+Murder+2018&user=&passkey=xxx&search=Hailey+Dean+Mystery%3A+A+Marriage+Made+for+Murder+2018&user=&passkey=xxx&search=Hailey+Dean+Mystery%3A+A+Marriage+Made+for+Murder+2018&user=&passkey=xxx 

Nothing is being snatched and brought to deluge

**Comment by j0nnymoe** [comment]
Best to report this directly to either Couchpotato or jackett as we only package the software into containers - this looks like an issue with the actual software.

**Comment by jang430** [comment]
Thank you j0nnymoe
