### ISSUE TITLE
Couchpotato not snatching torrents

### ISSUE THREAD

**Issue by JTT-JustTheTip** [linuxserver/docker-couchpotato#39]
OS - Ubuntu Server LTS 16.04, Docker  18.06.1-ce

Docker compose - 
`Radarr:
    image: linuxserver/radarr:latest
    hostname: radarr
    container_name: radarr
    environment:
      PUID: '1001'
      PGID: '1001'
      TZ: Europe/London
    network_mode: le_bridge
    restart: always
    volumes:
    - /Docker_Configs/Radarr/Config:/config
    - /media/AlphaMedia/Movies:/movies
    - /media/VMRoot/VMMedia/complete/movies:/downloads/complete/movies
    tty: true
    ports:
    - 7878:7878/tcp`

CP is able to find the torrents but it doesnt automatically add them to transmission, cant work out why not though as when i manually select one of the torrents its found it doesnt have any issues

Thanks!

**Comment by CHBMB** [comment]
OK, now I'm really confused, this is couchpotato, but you've posted Radarr docker compose.....

**Comment by JTT-JustTheTip** [comment]
I think the lack of sleep is really beginning to show now ahahaha,
`Coucnhpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    hostname: couchpotato
    environment:
      PUID: '1001'
      GUID: '1001'
      TZ: Europe/London
    network_mode: le_bridge
    volumes:
    - /Docker_Configs/Couchpotato/Config:/config
    - /media/AlphaMedia/Movies:/movies
    - /media/VMRoot/VMMedia/complete/movies:/complete/movies
    tty: true
    restart: always
    ports:
    - 5050:5050/tcp`

This is the one i meant to post.

**Comment by sconnery** [comment]
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: source:(CouchPotato:CouchPotatoServer master) 12ca4c22 (2018-03-31 22:29:42)
Running on: ...

### Logs:
```
12-22 12:38:28 ERROR [edia._base.providers.base] Failed to login TorrentLeech: unknown 
```

**Comment by sconnery** [comment]
for some reason torrent leech isnt playing nice :(

**Comment by CHBMB** [comment]
Gonna close this as it's an upstream issue as far as I can tell.
