### ISSUE TITLE
LXML and OpenSSL not available: Docker Compose

### ISSUE THREAD

**Issue by seesemichaelj** [linuxserver/docker-couchpotato#43]
I'm running the docker-compose.yml file on Ubuntu 18.04 Server and I receive the following errors (checked in the log) after startup.

```
03-23 01:52:18 ERROR [chpotato.core._base._core] LXML not available, please install for better/faster scraping suppor
t: `http://lxml.de/installation.html`
03-23 01:52:18 ERROR [chpotato.core._base._core] OpenSSL not available, please install for better requests validation
: `https://pyopenssl.readthedocs.org/en/latest/install.html`: Traceback (most recent call last):
  File "/opt/CouchPotatoServer/couchpotato/core/_base/_core.py", line 84, in dependencies
    import OpenSSL
ImportError: No module named OpenSSL
```

**Comment by sparklyballs** [comment]
that's not our container given the path in your log is 

`/opt/CouchPotatoServer/couchpotato`

and we install to `/app/couchpotato`

**Comment by seesemichaelj** [comment]
Ah, that would explain the mess. I used a different container, forgot to clear the config folder, then decided to use your container. I'm going to go ahead and close this (I have shifted to using Radaar haha). Thanks!

**Comment by seesemichaelj** [comment]
I can confirm that with a clean config folder that the docker image successfully starts and I can open the install wizard for couchpotato. Thanks!
