### ISSUE TITLE
Couchpotato deleted ~30tb of movies

### ISSUE THREAD

**Issue by jadechessink** [linuxserver/docker-couchpotato#46]
spun up couchpotato, noticed that my movies were dropping like flies. issue wasnt present until i switched to docker. 

OS:
ubuntu 18.04
[logs.zip](https://github.com/linuxserver/docker-couchpotato/files/3409349/logs.zip)

**Comment by tobbenb** [comment]
There is no way the container would delete the files. It's either a bug in couchpotato (Not sure if they even develop it anymore) or  something you did.

**Comment by thelamer** [comment]
Your logs are full of piracy shit. Closing and do not open another issue.
