### ISSUE TITLE
Couchpotato show Movie Folder as empty

### ISSUE THREAD

**Issue by BMWfan** [linuxserver/docker-couchpotato#47]
Hello i have a docker container running with couchpotato.

These are my start parameters:

`  docker create \
  --name=couchpotato \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Berlin \
  -e UMASK_SET=022 \
  -p 5050:5050 \
  -v /etc/couchpotato:/config \
  -v /mnt/ext-hdd/Downloads/complete:/downloads \
  -v /mnt/ext-hdd/nzb.to/movies:/movies \
  --restart unless-stopped \
  linuxserver/couchpotato:arm32v7-latest`

If i start a bash on the container via `docker exec -it couchpotato /bin/bash` and check the permissions, then it looks as its correct:
`drwxrwxrwx   1 root root  65536 Jul 29 17:51 movies`

but couchpotato shows me that the folder is empty.

How could it be, or how could i fix this?

drwxrwxrwx   1 root root  65536 Jul 29 17:51 movies

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by j0nnymoe** [comment]
Mount your drive as a normal user, not as root. The container can't see the files as everything is owned by root, not the user group.

**Comment by BMWfan** [comment]
@j0nnymoe depending on the permissions 777 should it be read and writeable by everyone. Also other folders could i choose with the same user as owner and there i can see the files.

So please reopen the case its not solved.

**Comment by CHBMB** [comment]
@BMWfan You are free to add more information, but FWIW I agree with @j0nnymoe 

You haven't included enough information for us to tell you any more despite the template we provided.~

```
<!--- If you have an issue with the project, please provide us with the following information -->

<!---  Host OS -->
<!--- Command line users, your run/create command, GUI/Unraid users, a screenshot of your template settings. -->
<!--- Docker log output, docker log <container-name>      -->
<!--- Mention if you're using symlinks on any of the volume mounts. -->
```

Specifically what filesystem those external hdds are using and what operating system you're using.

**Comment by BMWfan** [comment]
@CHBMB thanks for your answer.
Host OS: Raspbian GNU/Linux 10 (buster)
I start the Docker Container as also mentioned above with the following command:
`docker create \ --name=couchpotato \ -e PUID=1000 \ -e PGID=1000 \ -e TZ=Europe/Berlin \ -e UMASK_SET=022 \ -p 5050:5050 \ -v /etc/couchpotato:/config \ -v /mnt/ext-hdd/Downloads/complete:/downloads \ -v /mnt/ext-hdd/nzb.to/movies:/movies \ --restart unless-stopped \ linuxserver/couchpotato:arm32v7-latest`

As you can see in the command line, i map the folder /mnt/ext-hdd/Downloads/complete and /mnt/ext-hdd/nzb.to/movies. 

Here are the rights on the docker host for both:
drwxrwxrwx 1 root root 65536 Jul 29 16:51  movies
drwxrwxrwx 1 root root 40960 Dez 10  2017 complete

The files inside of the folder has the same permissions, user and group.

If i try to get the list of files of downloads which reference on the docker host to /mnt/ext-hdd/Downloads/complete over the movie library manager of couchpotato then i can see all the including files. If i do this with the movie folder it shows me as it would be empty.

Here is the docker log:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes
`
Filesystem of the external HDD is NTFS.
I mount this with ntfs-3g to the path /mnt/ext-hdd

I understand that the most problems are relying on permissions but why can in see the content of the download folder and not of the movie folder, both has the same permissions and lying on the same external hard drive.

Best Regards

Daniel

**Comment by j0nnymoe** [comment]
If you exec into the container `docker exec -u abc -it couchpotato /bin/bash` and browse to `/movies`, do you see anything in the folder when doing `ls -la` ?

**Comment by BMWfan** [comment]
@j0nnymoe, yeap. All files are listed.

**Comment by j0nnymoe** [comment]
It almost seems like an issue with couchpotato itself rather than anything you've done to setup the container. Though considering it hasn't had a release coming up to nearly 4 years now (Last being 31 Aug 2015), I'm not sure it'll get fixed (if there is an issue).
