### ISSUE TITLE
feature request: allow to set time for searches

### ISSUE THREAD

**Issue by godofjesters** [linuxserver/docker-couchpotato#53]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
ability to set timer for how often couchpotato should check each searcher. it appears to only check every day or 2 and i miss out on releases.

## Current Behavior
currently there is no where that i've found to set how often to search on the searchers.

## Environment

**OS:**      Debian (Docker container)
**CPU architecture:** x86_64
**How docker service was installed:**      
docker run command

## Command used to create docker container (run/create/compose/screenshot)

docker run --restart always -d --name=couchpotato -v /opt/CouchPotato:/config -v /mnt/storage/data/sort:/downloads -v /mnt/data/raid/media/movies:/movies -v /mnt/data/raid/encode:/encode -e PGID=100 -e PUID=1000 -e TZ=US/Pacific -p 5050:5050 linuxserver/couchpotato

## Docker logs
N/A

**Comment by aptalca** [comment]
That's something that needs to be implemented by the CouchPotato devs. We only package their app in a docker image.

**Comment by godofjesters** [comment]
thank you and i will!
