### ISSUE TITLE
Raspberry Pi 4: LXML and OpenSSL is missing 

### ISSUE THREAD

**Issue by kgorshkoff** [linuxserver/docker-couchpotato#54]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Fully working lxml and openssl libraries

## Current Behavior
[chpotato.core._base._core] OpenSSL not available, please install for better requests validation: `https://pyopenssl.readthedocs.org/en/latest/install.html`: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/_base/_core.py", line 84, in dependencies import OpenSSL ImportError: No module named OpenSSL
[chpotato.core._base._core] LXML not available, please install for better/faster scraping support: `http://lxml.de/installation.html`

## Steps to Reproduce
1. Install pyopenssl & lxml in host system
2. Run docker-compose
3. Run container

## Environment
**OS:**      Linux pi 5.4.61-v8+ #1339 SMP PREEMPT Tue Sep 1 18:58:26 BST 2020 aarch64 GNU/Linux
**CPU architecture:** aarch64
**How docker service was installed:**      
Openmediavault's plugin

## Command used to create docker container (run/create/compose/screenshot)
version: "2.1"
services:
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/Moscow
      - UMASK_SET=022
    volumes:
      - /srv/dev-disk-by-label-Main/appdata/couchpotato:/config
      - /srv/dev-disk-by-label-Main/media/downloads:/downloads
      - /srv/dev-disk-by-label-Main/media/movies:/movies
    ports:
      - 6005:5050
    restart: unless-stopped

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1002
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by aptalca** [comment]
According to cp github, those are optional dependencies. Normally we would add them, but alpine no longer publishes pip for python2 as py2 is EOL.

**Comment by kgorshkoff** [comment]
> According to cp github, those are optional dependencies. Normally we would add them, but alpine no longer publishes pip for python2 as py2 is EOL.

I installed them myself, but those modules still don't work. Can you please nudge me where should I look?

**Comment by aptalca** [comment]
What and how did you install?

**Comment by JohnCHarrington** [comment]
Many sources now force https, so the lack of openssl broke my install (no downloads ever found). I switched to an ubuntu base, installed openssl and lxml and it all worked great.

**Comment by vledder** [comment]
I'm having the same issue on my Synology running this docker container (using latest).

> 12-23 16:11:21 ERROR[chpotato.core._base._core] LXML not available, please install for better/faster scraping support: `http://lxml.de/installation.html`
> 12-23 16:11:21 ERROR[chpotato.core._base._core] OpenSSL not available, please install for better requests validation: `https://pyopenssl.readthedocs.org/en/latest/install.html`: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/_base/_core.py", line 84, in dependencies import OpenSSL ImportError: No module named OpenSSL 

Wondering what actions I can take to solve this? Due this no movies get scraped and lots of other functions (like dashboard) dont work cause of the errors like:

> ERROR[hpotato.core.plugins.base] Failed opening url in CouchPotatoApi: https://api.couchpota.to/messages/?last_check=0 Traceback (most recent call last): ConnectionError: ('Connection aborted.', gaierror(-3, 'Try again')) 
> ERROR[hpotato.core.plugins.base] Failed opening url in OMDBAPI: https://www.omdbapi.com/?apikey=xxx&type=movie&i=tt6878306 Traceback (most recent call last): ReadTimeout: HTTPSConnectionPool(host='www.omdbapi.com', port=443): Read timed out. (read timeout=3) 

@JohnCHarrington which ubuntu base(container) are you referring to?

**Comment by JohnCHarrington** [comment]
I just created my own image, used ubuntu 18.04 LTS and installed couchpotato, LXML and OpenSSL. Works great apart from my config files don't get stored in the right place so they disappear when I restart - should be easy to fix though, just need to work out the right mount folder for them :)

**Comment by vledder** [comment]
I decided to install nzbhydra next to Couchpotato. Nzbhydra is now taking care of the searches whilst being connected to CP. No more LXML and OpenSLL issues since the connect on my internal http. Maybe this will help other people too.

**Comment by aptalca** [comment]
With python2 being EOL and getting removed from recent OS bases, I don't think couchpotato will be supported by us much longer. The upstream project has been on life support for years

**Comment by Donnie1992** [comment]
I'm having the same issue but on a omv build running through docker.
This happened with the last update wich then got reverted again and now it's happening again.
