### ISSUE TITLE
Add var  for OMDB_API

### ISSUE THREAD

**Issue by tm9k1** [linuxserver/docker-couchpotato#59]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

There should be a var OMDB_API_KEY in which I can add my OMDB API key

## Current Behavior

Logs have errors like
```
[hpotato.core.plugins.base] Failed opening url in OMDBAPI: https://www.omdbapi.com/?apikey=xxx&type=movie&y=&t=hit Traceback (most recent call last): HTTPError: 401 Client Error: Unauthorized for url: https://www.omdbapi.com/?apikey=xxx&type=movie&y=&t=hit
```
## Alternatives Considered

None so far. Suggestions are welcome!

**Comment by aptalca** [comment]
Can't you add it in the gui?

**Comment by tm9k1** [comment]
I couldn't find the gui option for this in settings, can you please send an
ss or quick guide?

**Comment by j0nnymoe** [comment]
Looks like you add it directly to the settings.conf : https://github.com/CouchPotato/CouchPotatoServer/pull/7214
