### ISSUE TITLE
CouchPotato not respecting UID and GID

### ISSUE THREAD

**Issue by kmlucy** [linuxserver/docker-couchpotato#9]
I created the image using:
`docker create --name="CouchPotato" -v /etc/localtime:/etc/localtime:ro -v /opt/couchpotato:/config -v /mnt/downloads:/downloads -v /mnt/movies:/movies -e PGID=1003 -e PUID=118 -p 5050:5050 linuxserver/couchpotato
`
The permissions on the download folder are: `drwxrwxr-- 2 kyle torrents`
The permissions on the movies folder are: `drwxrwxr-- 2 kyle media`
The permissions on the config folder are: `drwxr-xr-x  3 couchpotato couchpotato`

The user 'couchpotato' has a UID of 118, and GID of 1003, with it the 'couchpotato' group. If I run `groups couchpotato`, I get a result of `couchpotato : couchpotato media torrents`, so the user 'couchpotato' should have read/write access all three of those folders. The config folder works fine, but both the download and movies folders show as empty when I select them in renamer. Renamer also does not pick up on any movies in the downloads folder when run.

**Comment by sparklyballs** [comment]
ideally any folders accessed by this (or any other docker) should be owned by the user correspoding to PUID set in docker run/create.

**Comment by gbrks** [comment]
The user within the docker itself will need to be a member of the other two groups.
`docker exec -it couchpotato /bin/bash`
`groups abc`
In this case you will need to manually add the `media` and `torrents` groups (with the same GID as the host) to the `abc` user inside the container.

**Comment by kmlucy** [comment]
That fixes it, thanks.

**Comment by simonk83** [comment]
Hi all,

Really sorry to drag this up but I'm totally new to Docker (and not particularly great with Unix) so was wondering if someone would be kind enough to give me a bit of a step by step command list to sort this out?

My container is just called the default linuxserver-couchpotato1, and I followed this guide (http://drfrankenstein.co.uk/2016/04/11/setting-up-couchpotato-in-docker-on-a-synology-nas/), so after determine my user accounts privileges, I set my PGID to 101 and PUID to 0.

Like a complete noob I ran the commands listed above and got the following:

```
/volume1/docker/couchpotato# docker exec -it linuxserver-couchpotato1 /bin/bash
root@linuxserver-couchpotato1:/app/couchpotato$ groups
root bin daemon sys adm disk wheel floppy dialout tape video
root@linuxserver-couchpotato1:/app/couchpotato$ groups abc
abc users
```

Just not really sure what I'm doing ;)

**Comment by CHBMB** [comment]
What is the issue?

**Comment by simonk83** [comment]
Sorry, probably should have explained that ;)

Couchpotato loads fine, but if I go to Manage or Renamer I can't see any folders listed, it just says "Selected folder is empty".   Because of this I can't get CP to scan my current movies folder, and while i haven't tried downloading anything yet I'm assuming the renamer will fail as well.

Can't quite get my head around how to add my download and movies directories to CP

**Comment by j0nnymoe** [comment]
You need to read the bit on the page you linked about opening advancedsettings and adding your shares to the docker :)

**Comment by simonk83** [comment]
They're in there ;)   I've added a bunch of detail (or crap) to my initial post above, not sure if that helps at all. Been at this a long time now so I'm all over the place ;)

**Comment by simonk83** [comment]
<img width="691" alt="volume" src="https://cloud.githubusercontent.com/assets/518440/19150908/5c8047de-8c15-11e6-919c-71a6810594b7.png">
<img width="665" alt="environ" src="https://cloud.githubusercontent.com/assets/518440/19150910/5dca3d7a-8c15-11e6-9899-d392f3973d0b.png">

**Comment by j0nnymoe** [comment]
ok, so inside CP, your movies will be located to /movies and your downloads goto /downloads. 
Obviously make sure the user you have set as the PUID has access to these shares.

**Comment by simonk83** [comment]
The user Simon (that's who I log into the DS with) has Read/Write to the NAS folder (Movies and SabMovies are in there).

When you say make sure that user (listed as 1053 unless I've stuffed that up too) has access to the shares, do you mean Movies and SabMovies, or the "mapped" /movies and /downloads. If that latter, how do I go about doing that (sorry in advance)?

**Comment by j0nnymoe** [comment]
they need to have access to your NAS shares (outside the docker).
Unfortunately my knowledge of the Syno gui is zero so not very useful help. 
I highly suggest rolling back and start setting up the container fresh and see if the same thing happens again.

**Comment by simonk83** [comment]
They do indeed have access to the NAS shares.   I think you're right about rolling back, I might have to try that. I've been changing permissions on files left right and center :D

**Comment by simonk83** [comment]
God.

Killed the install and reloaded from scratch.  Immediately hit the same issue, then my brain finally decided to come to the party and suggested I try a different browser.   Chrome apparently hates me (probably an adblock extension or something), and Safari of all things saved the day.  Never thought I'd hear myself say that.

Sorry for the noobishness and wasting your collective time ;)

**Comment by j0nnymoe** [comment]
No problem, glad you got it sorted :)
